FROM node:22-alpine

WORKDIR /app

COPY multimodal-ui/ ./

CMD \
  echo "Running: npm install" && \
  npm install && \
  echo "Running: npm run build" && \
  npm run build && \
  echo "Running: cp -r ./dist/multimodal-ui/browser/** static/" && \
  cp -r ./dist/multimodal-ui/browser/** static/