FROM node:18 as build-stage

WORKDIR /app

COPY multimodal-ui/package*.json ./

RUN npm ci

COPY multimodal-ui .

RUN npm run build -- --configuration production

FROM nginx:alpine

COPY --from=build-stage /app/dist/multimodal-ui/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]