version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "${PORT_CLIENT}:80"
    networks:
      - multimodal-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:${PORT_SERVER}

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - PORT_SERVER=${PORT_SERVER}  # Moved under 'build'
    env_file:
      - .env
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    volumes:
      - ./multimodal-server:/app/multimodal-server
      - ./data:/app/data
    networks:
      - multimodal-network
    environment:
      - SERVER_HOST=0.0.0.0
      - PORT=${PORT_SERVER}

networks:
  multimodal-network:
    driver: bridge