version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8085:80"
    networks:
      - multimodal-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8090

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8090:8090"
    volumes:
      - ./multimodal-server:/app/multimodal-server
      - ./data:/app/data
    networks:
      - multimodal-network
    environment:
      - SERVER_HOST=0.0.0.0

networks:
  multimodal-network:
    driver: bridge