FROM python:3.11.12-alpine3.21

WORKDIR /app/python

COPY python/requirements.txt /app/python/

RUN echo "Running: pip install --upgrade pip -r requirements.txt" && \
  pip install --upgrade pip -r requirements.txt

CMD echo "Running: viewer start" && \
  viewer start