version: '3.8'
services:
  build-ui:
    container_name: build-ui
    build:
      context: .
      dockerfile: Dockerfile.build-ui
    profiles:
      - build-ui
      - publish
      - publish-test
    volumes:
      - ./python/multimodalsim_viewer/ui/static:/app/static

  publish:
    container_name: publish
    build:
      context: .
      dockerfile: Dockerfile.publish
    depends_on:
      build-ui:
        condition: service_completed_successfully
    profiles:
      - publish
    volumes:
      - ./python:/app/python

  publish-test:
    container_name: publish-test
    build:
      context: .
      dockerfile: Dockerfile.publish-test
    depends_on:
      build-ui:
        condition: service_completed_successfully
    profiles:
      - publish-test
    volumes:
      - ./python:/app/python

  publish-only: # Do not require build-ui
    container_name: publish-only
    build:
      context: .
      dockerfile: Dockerfile.publish
    profiles:
      - publish-only
    volumes:
      - ./python:/app/python

  publish-test-only: # Do not require build-ui
    container_name: publish-test-only
    build:
      context: .
      dockerfile: Dockerfile.publish-test
    profiles:
      - publish-test-only
    volumes:
      - ./python:/app/python
