FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y git

# Copy entire project
COPY . .

# Install the package and dependencies
RUN pip install --upgrade pip && \
    cd multimodal-simulator/python && \
    pip install -r requirements.txt && \
    python setup.py install && \
    cd ../.. && \
    pip install -e .

EXPOSE ${PORT_SERVER}

CMD ["multimodal-server"]