FROM python:3.11.12-alpine3.21

WORKDIR /app/python

COPY python/requirements.txt python/setup.py /app/python/

RUN pip install --upgrade pip -r requirements.txt

RUN python -m pip install --upgrade -e .

CMD ["viewer", "start"]