FROM node:22-alpine

WORKDIR /app/angular

COPY multimodal-ui/package.json multimodal-ui/package-lock.json ./

RUN echo "Running: npm install" && \
  npm install

CMD echo "Running: npm start" && \
  npm start


