FROM node:22 as build-stage

WORKDIR /app

COPY multimodal-ui/package*.json ./

RUN npm ci

COPY multimodal-ui .

COPY .env ./

RUN npm run build 

FROM nginx:alpine

RUN apk add --no-cache bash

COPY --from=build-stage /app/dist/multimodal-ui/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf.template

CMD ["/bin/bash", "-c", "envsubst '${PORT_SERVER}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
EXPOSE 80