version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "${PORT_CLIENT}:80"  # Only expose port 80
    networks:
      - multimodal-network
    depends_on:
      - backend
    environment:
      - PORT_SERVER=${PORT_SERVER}

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    networks:
      - multimodal-network
    environment:
      - SERVER_HOST=0.0.0.0
      - PORT=${PORT_SERVER}

networks:
  multimodal-network:
    driver: bridge