FROM node:22-alpine

WORKDIR /app

COPY multimodal-ui/ /app/angular

COPY default-environment.json /app/

CMD \
  echo "Running: cd /app/angular" && \
  cd /app/angular && \
  echo "Running: npm install" && \
  npm install && \
  echo "Running: npm run build" && \
  npm run build && \
  echo "Running: cp -r ./dist/multimodal-ui/browser/** /app/static/" && \
  cp -r ./dist/multimodal-ui/browser/** /app/static/