FROM python:3.11.12-alpine3.21

# Set the working directory
WORKDIR /app

# Copy the requirements file for building the package
COPY python/requirements.build.txt python/requirements.txt /app/

# Update pip and install dependencies
RUN python -m pip install --upgrade pip -r requirements.build.txt

# Copy the Python package files
COPY .pypirc ./

# Copy default environment file
COPY .env /app/

# Set the environment variable for the Python package version by getting it from the docker compose file
ARG PYTHON_PACKAGE_VERSION

# Publish the package to PyPI
CMD \
  echo "Running: cd ./python" && \
  cd ./python && \
  echo "Running: cp ../.env ./multimodalsim_viewer/common/environments/.env" && \
  cp ../.env ./multimodalsim_viewer/common/environments/.env && \
  echo "Running: rm -rf ./dist" && \
  rm -rf ./dist && \
  echo "Running: rm -rf multimodalsim_viewer.egg-info" && \
  rm -rf multimodalsim_viewer.egg-info && \
  echo "Running: PYTHON_PACKAGE_VERSION=${PYTHON_PACKAGE_VERSION} python -m build" && \
  PYTHON_PACKAGE_VERSION=${PYTHON_PACKAGE_VERSION} python -m build && \
  echo "Running: python -m twine upload --repository testpypi --verbose --config-file .pypirc ./dist/*" && \
  python -m twine upload --repository testpypi --verbose --config-file ../.pypirc ./dist/* \ 