name: Build

on:
  workflow_dispatch:

  # TODO REMOVE THIS
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to ensure we can push changes
          ref: ${{ github.head_ref }} # Checkout the current branch to ensure we are on the correct commit
          token: ${{ secrets.WORKFLOW_PAT }} # Use the personal access token for authentication

      # TODO REMOVE THIS
      - name: Git status
        run: |
          git status

      # TODO REMOVE OTHER BUILD COMMITS IN HISTORY

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./multimodal-ui

      - name: Run build in production mode
        run: npm run build:prod
        working-directory: ./multimodal-ui

      - name: Clear previous build artifacts
        run: rm -rf ./multimodal-ui-python/multimodal_ui/static

      - name: Copy build artifacts
        run: cp -r ./multimodal-ui/dist/multimodal-ui/browser/ ./multimodal-ui-python/multimodal_ui/static\

      - name: Verify if changes have been made
        id: verify-build
        run: |
          if git diff --exit-code --name-only; then
            echo "No changes detected in the build artifacts."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in the build artifacts."
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Do not push if no changes were made
        if: steps.verify-build.outputs.changes_detected == 'false'
        run: |
          echo "No changes detected. Skipping commit and push."
          exit 0

      - name: Commit and push changes
        if: steps.verify-build.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./multimodal-ui-python/multimodal_ui/static
          git commit -m "_____automatic-build-update_____"
          git push
