name: Build Angular

on:
  workflow_call:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./multimodal-ui

      - name: Build Angular application
        run: npm run build
        working-directory: ./multimodal-ui

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build-artifacts
          path: ./multimodal-ui/dist/multimodal-ui/browser
