# https://stackoverflow.com/questions/63745613/how-to-get-a-branch-name-on-github-action-when-push-on-a-tag
name: Build Angular

on:
  workflow_call:

jobs:
  verify-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure that the full history is fetched

      - name: Verify branch
        run: |
          # Get the current branch name
          BRANCH_NAME=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          echo "Current branch: $BRANCH_NAME"
          # Check if the branch is 'main'
          if [ "$BRANCH_NAME" != "main" ]; then
            echo "This workflow can only be run on the 'main' branch."
            exit 1
          fi
