name: Verify Angular format and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./multimodal-ui

      - name: Run format check
        run: npm run format:check
        working-directory: ./multimodal-ui

      - name: Run lint check
        run: npm run lint
        working-directory: ./multimodal-ui
