name: Verify Python format and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -r requirements.txt
        working-directory: ./python

      - name: Run format check
        run: |
          black --check --diff .
          isort --check --diff .
        working-directory: ./python

      - name: Run lint check
        run: |
          pylint .
        working-directory: ./python
